// Action Types
export const GET_MESSAGES_REQUEST = 'GET_MESSAGE_REQUEST';
export const GET_MESSAGES_FULFILLED = 'GET_MESSAGES_FULFILLED';
export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE';

export const ADD_MESSAGE_REQUEST = 'ADD_MESSAGE_REQUEST';
export const ADD_MESSAGE_FULFILLED = 'ADD_MESSAGE_FULFILLED';
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE';

export const GET_CONTACTED_REQUEST = 'GET_CONTACTED_REQUEST';
export const GET_CONTACTED_FULFILLED = 'GET_CONTACTED_FULFILLED';
export const GET_CONTACTED_FAILURE = 'GET_CONTACTED_FAILURE';
